### ISSUE TITLE
Subtle bug in TooN::normalize()

### ISSUE THREAD

**Issue by xtrawurst** [edrosten/TooN#10]
Using TooN::normalize() (helpers.h) with a const Vector does not make sense but will compile fine, however the compiler will select the "other" TooN::normalize() that's supposed to only work on vector slices. Since that normalize() uses a by-value argument, no normalization takes place.

Using TooN::normalize() with a const Vector should have the compiler complain instead.

**Comment by edrosten** [comment]
Hi,

Good catch, thanks for the report.

sent from phone.

**Comment by edrosten** [comment]
Hi,


I'm not 100% sure this is a bug. It's certainly an unintended consequence.
It's there so you can normalise a slice: without it you can't do
normalize(vec.slice<1,2>()) for example, because the latter won't work on a
reference.

It is, however nonsensical.

I believe the only reasonable solution is to move to a more modern C++ and
use an r-value reference. I'll look into that.


-Ed

**Comment by edrosten** [comment]
Hi,

OK, that didn't take too long!

If you pull the latest version out of git, then the nonsensical code won't
compile any more. Note you have to use C++11 or newer.

-Ed

**Comment by xtrawurst** [comment]
Great, thanks for the quick fix!

Rafael

Rafael Spring
CTO, Co-Founder
DotProduct LLC / DotProduct GmbH
rafael@dotproduct3d.com
www.dotproduct3d.com
m: +49 1525 3822738
@DotProduct3D
